### PR TITLE
Black lager module

### LINKED ISSUE #5: Create black lager module in meshtastic

### PR DESCRIPTION
**Pull request by ahmedkadd**
Close #5

Create a meshtastic module called black lager for the signed messaging

### CODE REVIEW

**Comment by joshx1** [comment]
The code looks good. Could you add some documentation for the BlackLagerModule.cpp file? Perhaps giving an overview of what it is doing and what it is to be used for.

**Review by DatFob — APPROVED** [review]

**Review by joshx1 — CHANGES_REQUESTED** [review]
Looks good but leave some comments for the BlackLagerModule.cpp file, an overview of the file will be sufficient.

**Comment by ahmedkadd** [comment]
> Looks good but leave some comments for the BlackLagerModule.cpp file, an overview of the file will be sufficient.

Added documentation to the BlackLagerModule class

**Review by joshx1 — APPROVED** [review]
Documentation is good!

**Pull request merged**
